FROM bilke/ogs-cli
MAINTAINER Lars Bilke <lars.bilke@ufz.de>

RUN apt-get install -y qt4-dev-tools
RUN apt-get install -y libgeotiff-dev
RUN apt-get install -y libxt-dev
RUN wget http://www.opengeosys.org/images/dev/vtk-6.tar.gz
RUN tar -xf vtk-6.tar.gz
